app/login/urls.py
from django.urls import path

from . import views

#app_name是命名空间
app_name = "login"

urlpatterns = [
    #注册页面
    path("register", views.register_index, name="register"),
    #注册API
    path("register_API/", views.register_API, name="register_API"),
    #登录页面
    path("", views.login_index, name="login"),
    #登录API
    path("login_API/", views.login_API, name="login_API"),
    #登出API
    path("logout/", views.logout, name="logout"),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #login应用的主路由
    path('login/',include('login.urls')),
    #dashboard应用的主路由
    path('',include('dashboard.urls')),
    #polls应用的主路由
    path('polls/',include('polls.urls')),
]
# 仅在开发模式下添加媒体文件URL路由
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/login/models.py
from django.db import models


class userInfo(models.Model):
    account = models.CharField(
        verbose_name='账号',
        max_length=20,
        unique=True,
    )
    name = models.CharField(
        verbose_name='姓名',
        max_length=10,
        help_text='请输入姓名',
    )
    email = models.EmailField(
        verbose_name='邮箱',
        unique=True,
    )
    password = models.CharField(
        verbose_name='密码',
        max_length=16,
        help_text='请输入密码',
    )
    register_time = models.DateTimeField(
        verbose_name='创建时间',
        auto_now_add=True,
    )
    avatar_name = models.CharField(
        verbose_name='头像名称',
        max_length=150,
        blank = True,
        null = True,
        help_text = '用户头像的文件名',
    )

    class Meta:
        db_table = 'tb_user'
        verbose_name = '用户信息'
        verbose_name_plural = '用户信息'

app/login/views.py
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from login.models import userInfo


def register_index(request):
    return render(request, 'register.html')

def register_API(request):

    if request.method == "POST": #如果接收到前端传来的POST请求
        #获取数据
        name = request.POST.get("name", "").strip()
        account = request.POST.get("account", "").strip()
        email = request.POST.get("email", "").strip()
        password = request.POST.get("password", "").strip()



        # 验证必填字段,目前还未完成
        errors = {}

        if not name:
            errors["nameErr"] = "请填写姓名!"

        if not account:
            errors["accountErr"] = "请填写账号!"

        if not email:
            errors["emailErr"] = "请填写邮箱!"

        if not password:
            errors["passwordErr"] = "请填写密码"

        if userInfo.objects.filter(account=account).exists():
            errors["accountErr"] = "账号已存在!"

        if userInfo.objects.filter(email=email).exists():
            errors["emailErr"] = "邮箱已存在!"


        if errors:

            context = errors.copy()

            #此处将前端传来的name, account, email更新到context中，
            # 以便在前端页面中显示用户输入的内容，而不是清空
            context.update({
                "name": name,
                "account": account,
                "email": email,
            })
            return render(request, "register.html", context)


        try:
            userInfo.objects.create(
                name=name,
                account=account,
                email=email,
                password=password,
            )

            request.session["account"] = account

            return redirect(reverse('login:login'))

        except IntegrityError:

            errors["accountErr"] = "注册失败，请检查账号或邮箱是否已被使用!"
            context = errors.copy()
            context.update({
                "name": name,
                "account": account,
                "email": email,
            })

            return render(request, "register.html", context)

    return redirect(reverse('login:register'))


def login_index(request):
    return render(request, 'login.html')


def login_API(request):

    if request.method == "GET":

        account = request.GET.get("account", "").strip()
        password = request.GET.get("password", "").strip()

        queryset = userInfo.objects.filter(account=account)

        if not account or not password:
            return render(request, "login.html", {
                "nameErr": "请填写账号和密码",
            })

        if not(queryset.exists()):

                return render(request, "login.html", {
                    "nameErr": "账号不存在!",
                })

        queryset = queryset.filter(password=password)

        if not(queryset.exists()):
                return render(request, "login.html", {
                    "pswErr": "密码错误!",
                })

        #下面这个HTTPResponse是为测试用途，实际项目中应接login_API后续事务
        #return HttpResponse("登录成功!")



        request.session["account"] = queryset[0].account
        # 清除旧的session数据，确保登录状态正确
        request.session.modified = True
        return redirect(reverse('dashboard:index'))

def logout(request):
    # 清除session数据，确保登出状态正确
    request.session.flush()
    return redirect(reverse('login:login'))

app/login/templates/login.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DjangoVote - 登录</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    <div class = "center-container">

        <form id="login-Form" class = "register-card" method="get" action = "{% url 'login:login_API' %}">
            {% csrf_token %}
            <!-- 用户名 -->
            <h2 class = "form-title">登录</h2>
            <div style = "margin-bottom: 20px;">
                <label for="account">账号<sup>*</sup></label>
                <input class = "input-line" type="text" id="account" name="account" value="{{ userAccount }}" placeholder = "请输入账号" required>
                <div class="error-tip" id="nameErr" style="visibility: visible;">{{ nameErr }}</div>
            </div>
            <br>
            <!-- 密码 -->
            <div style = "margin-bottom: 20px;">
                <label for="password">密码<sup>*</sup></label>
                <input class = "input-line" type="password" id="password" name="password" placeholder=" 请输入密码" required>
                <div class="error-tip" id="pswErr" style="visibility: visible;">{{ pswErr }}</div>
            </div>
            <!-- 登录按钮 -->
            <button type="submit" class="btn">登录</button>
            <div class="form-footer">
            <!-- 如果未开发完注册业务先注释掉该行 -->
            没有账号？<a href="{% url 'login:register' %}">去注册</a>
            </div>

        </form>
    </div>

</body>
</html>

app/login/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DjangoVote - 注册</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    <div class = 'center-container'>
        <form id="register-Form" class = "register-card" action="{% url 'login:register_API' %}" method="post">
            {% csrf_token %}
            <!-- 姓名 -->
            <h2 class="form-title">注册账号</h2>
            <div style = "margin-bottom: 15px;">
                <label for="name">姓名<sup>*</sup></label>
                <input style = "width: 80%; padding: 8px;" type="text" id="name" name="name" value="{% if name %}{{ name }}{% endif %}" placeholder="请输入真实姓名" required>
                <div class="error-tip" id="nameErr" style="visibility: visible;">{{ nameErr }}</div>
            </div>
            <!-- 账号 -->
            <div style = "margin-bottom: 15px;">
                <label for="account">账号<sup>*</sup></label>
                <input style = "width: 80%; padding: 8px;" type="text" id="account" name="account" value="{% if account %}{{ account }}{% endif %}" placeholder="请输入账号" required>
                <div class="error-tip" id="accountErr" style="visibility: visible;">{{ accountErr }}</div>
            </div>
            <!-- 邮箱 -->
            <div style = "margin-bottom: 15px;">
                <label for="email">邮箱<sup>*</sup></label>
                <input style = "width: 80%; padding: 8px;" type="email" id="email" name="email" value="{% if email %}{{ email }}{% endif %}" placeholder="请输入邮箱" required>
                <div class="error-tip" id="emailErr" style="visibility: visible;">{{ emailErr }}</div>
            </div>

            <!-- 密码 -->
            <div style = "margin-bottom: 15px;">
                <label for="password">密码<sup>*</sup></label>
                <input style = "width: 80%; padding: 8px;" type="password" id="password" name="password" placeholder="请输入密码" required>
                <div class="error-tip" id="passwordErr" style="visibility: visible;">{{ passwordErr }}</div>
            </div>

             <button  type="submit" class="btn">立即注册</button>

            <div class="form-footer">
                <!-- 如果未开发完登录业务先注释掉该行 -->
                已有账号？<a href="{% url 'login:login' %}">去登录</a>
            </div>

        </form>

    </div>

</body>

</html>